### ISSUE TITLE
Error on compile

### ISSUE THREAD

**Issue by Bajoja** [BZHDeveloper/Json-Vala#2]
When i try to compile the examples that you provide, i recive this error.

![deepinscreenshot20170509215422](https://cloud.githubusercontent.com/assets/10621831/25872416/83fea882-3502-11e7-9c6d-99a73925bfaa.png)

**Comment by BZHDeveloper** [comment]
'-lm' lib is missing from pkg-config file.
I have pushed fix. but this repository is obsolete, JSON library is now on this repository : https://github.com/BZHDeveloper/vul

**Comment by Bajoja** [comment]
Thanks, i'm not notice that was a new repo.

**Comment by BZHDeveloper** [comment]
new repo with Text Encoding and reader / writer

**Comment by Bajoja** [comment]
Can you provide Json examples, or is the same from the other one?

I try with one of the other example and replace Json for GJson and --pkg json-vala for --pkg gjson-1.0 and giving error.

![captura de ecra de 2017-05-12 14-16-19](https://cloud.githubusercontent.com/assets/10621831/25999598/a644b3ce-371d-11e7-98ee-8ba3f8e99d55.png)
